### ISSUE TITLE
m_proxy is missing

### ISSUE THREAD

**Issue by Natulux** [imReker/wxWebViewBlink#2]
Hey. While trying to use CEF I found your post about not using that monster and rather have this minimalistic approach.
Thanks for your work!

When I try to compile according to your introduction, I get the compiler error that "m_proxy is not defined", first used in "void wxWebViewMiniBlink::SetProxy(const wxString& proxy)"

I use wxWidgets 3.1.0 on msWindows 10 x64. I also tried my self compiled wxWidgets from 1st of November 2018. And I use the precompiled Node.dll from your download.

I checked the online repository from wxWidgets and wxWebCiewBlink for m_proxy, but it is nowhere to be found. Where is it supposed to be defined?

Thank you.
Natulux

**Comment by imReker** [comment]
Fixed

**Comment by Natulux** [comment]
Wow, I never estimated a response as fast as yours. Thanks, it compiles fine now! :-)
