### ISSUE TITLE
GetPageSource returns Error

### ISSUE THREAD

**Issue by Natulux** [imReker/wxWebViewBlink#4]
wxWebViewMiniBlink::GetPageSource() returns the error: "Error running JavaScript: Reference Error: $ is not defined"

I am by no means a web developer, so I didn't set up a pull request. But I was able to work arround this by altering the called JS-Code.

I changed this:

`wxString result;`
`(const_cast<wxWebViewMiniBlink*>(this))->RunScript("$('html').html();", &result);`
`return result;`

To this:

`wxString result;`
`(const_cast<wxWebViewMiniBlink*>(this))->RunScript("document.getElementsByTagName('html')[0].innerHTML", &result);`
`return result;`

It works for me.

Best Natu

**Comment by imReker** [comment]
😄  Thx。
Btw, the source code returned is not origin source code received from the server. It's local source including changes made by JS.

**Comment by Natulux** [comment]
Good to know, thanks for the hint. ;-)

**Comment by Natulux** [comment]
Hello again
After I was able to compile node with the new master, I replaced the precompiled node.dll from your branch with the new compiled node.dll from weolars branch. Now I have the issue, that RunScript() does always return 'undefined'. (I can't get the InnerHTML as described above anymore)

Can you tell me about any changes your branch did to the MiniBlink project, so that RunScript would return something?

Thanks!

**Comment by imReker** [comment]
You need to change RunScript to use wkeRunJsByFrame with `isInClosure` param set to false

**Comment by Natulux** [comment]
Thank you!
