### ISSUE TITLE
Set Language

### ISSUE THREAD

**Issue by Natulux** [imReker/wxWebViewBlink#5]
I tried to change the standard language, because even here in europe the standard charset is chinese (maybe GB18030).

I used:
`wkeSetLanguage(m_webview, "UTF-8"); `
And also tried:
`wkeSetLanguage(m_webview, "ISO-8859-1"); //Latin-1`
Both made google.com to load in my language, but if I use a right click, it is still with chinese letters. Is there another option to set the language that I didn't see?

Thanks
Natu

**Comment by imReker** [comment]
It's only affect webpage's language. I think the context menu of MiniBlink has not been internationalized yet. You can change the menu string in source code by yourself.
It's a MiniBlink related problem, so I'll close this issue. You can post this issue to MiniBlink.
