### ISSUE TITLE
console for console.logs

### ISSUE THREAD

**Issue by Natulux** [imReker/wxWebViewBlink#6]
Hey,
I would like to catch console.log in my frame. Do you know if miniBlink provides a console and if I can access that console with WebViewMiniBlink?
I saw ShowDevTool (which I couldnt bring to show something interesting), but I know that devTools have a console - so I should be able to catch those logs, shouldn't I?

Thanks
Natu

**Comment by imReker** [comment]
You need specify the path of devtool page. Get it in release package of Miniblink.

**Comment by Natulux** [comment]
I tried and searched for some time now, couldn't get this to work - the devtools page opens but is blanc. What I don't understand: I include the whole miniblink backend via the node.dll. Are the devtools not part of the dll?
As I understand it, usually the devtools are connected via a debug port to the host. The host is in my case the webview or rather my project, containing the webview. So I have to copy the devtools dir from the third party webkit and ship it together with my project files? Also, in my case, I am not really hosting a webserver - I merely show my html in the webview.

I had a look at the prebuild miniblink project "wkexe.exe", which is able to open the devtools with the "Test" button. But I couldn't find it in the project files. If I could just clone that, I would be very glad. ;-)

Thanks
Natu

Edit:
I am pretty sure by now that it is the fault of my virtual file system again. I don't yet understand where the devtools read their input from, but if they try to get it from the files directly, they wouldn't find those files.

**Comment by Natulux** [comment]
Confirmed. If I use actual files and third party devtools, I can use them.
Sadly, thats no option for me. Im going to ask weolar, if there is a console that I could use.

**Comment by imReker** [comment]
I mean extract the `front_end` folder in Miniblink Release package to your hard drive and specify path to it in your code. The Chrome inspect tool is written in HTML and not included in Miniblink's dll, and the `front_end` is the official source file name of inspect tool's front-end.

Search: `RootWindow::onShowDevtools` in `miniblink-190410.rar\vip_demo_src\RootWindow.cpp`
