### ISSUE TITLE
Set Focus to the browser

### ISSUE THREAD

**Issue by Natulux** [imReker/wxWebViewBlink#7]
Hi,

I am not quite sure if this problem is related to the MiniBlink or the webview or both, but:
I load a page with an text field element, which has auto focus. But if I start typing, nothing reaches the element. The frame (window) has focus, though.
I tried:
`//With:
//const char* backend = wxWebViewBackendMiniBlink;
//m_browser = wxWebView::New(this, ID_WEBVIEW, "", wxDefaultPosition, wxDefaultSize, backend);

this->SetFocus();
this->SetFocusFromKbd();
m_browser->SetFocus();
m_browser->SetFocusFromKbd();`

But the browser still doesn't get the focus. Do you have any experience with that issue?

Thanks.
Natu

**Comment by imReker** [comment]
Override `SetFocus` and use `wkeSetFocus` within it.

**Comment by Natulux** [comment]
Ah I see. The m_browser->SetFocus function is calling the wxWindow::SetFocus at the moment, I wasn't aware of that. I attempted to override it in WebViewMiniBlink.cpp, but still wxWindow::SetFocus is called.
Do you suggest to override the SetFocus in wxWebView (but in the wxWebView class I wouldn't have wkeSetFocus available..)?
I am not quite sure how to override, because MiniBlink is just included as the backend, the class used is still wxWebView, and I don't know how exactly that works to be honest.

I have called wkeSetFocus( ) in "wxWebViewMiniBlink::OnDocumentReady" but that does not have any effect.

EDIT:
Since SetFocus is not overridden in wxWebView, I cant override it in WebViewMiniBlink. I guess it would be simpler to just write a custom focus function and call that. Is there a way to call a non static function from wxWebViewMiniBlink? The browser object is of type WebView and can only call functions, which also exist in WebView. 
Thank you :-)

**Comment by imReker** [comment]
Strange, `wkeSetFocus` should work within `OnDocumentReady`.

`wxWebViewMiniBlink` inherit from `wxWebView`, so it's a `wxWebView` control, not 'backend'.
See https://github.com/imReker/wxWebViewBlink/blob/878c2169e51abc2a0c1b8eef3ecc6dc24e1f73aa/WebViewMiniBlink.h#L37

**Comment by Natulux** [comment]
To answer my own question:
I could invoke a custom function with:
`wxWebViewMiniBlink* browserBackend = (wxWebViewMiniBlink*)m_browser->GetNativeBackend();
	browserBackend->SetFocus_browser();`

and
`void wxWebViewMiniBlink::SetFocus_browser()
{
	wkeSetFocus(m_webview);
}`
That creates an exception though.

I will continue with your suggestion to see, if I get an error.

**Comment by Natulux** [comment]
Well, the console was blanc.
But you were right: I can call wkeSetFocus in OnDocumentReady, I don't know what I messed up the first time.
I still don't understand the whole concept and struggle to alter the backend and your wrapper to my needs, but thanks anyway. So far it is not too bad. :-)

**Comment by imReker** [comment]
I mean you can freely add function to `wxWebViewMiniBlink`.
And `m_browser->GetNativeBackend()` is wrong, you should use `m_browser->SetFocus_browser()`

**Comment by Natulux** [comment]
Yes, I noticed.
GetNativeBackend returns the pointer to m_webview:
`wkeWebView wkeweb = (wkeWebView)m_browser->GetNativeBackend()`

But `m_browser->SetFocus_browser()` does not work, because `wxWebView* m_browser;` is not a WebViewMiniBlink. And I can't easily change it that way, because it is initialized with
`m_browser = wxWebViewMiniBlink::New(this, ID_WEBVIEW, "", wxDefaultPosition, wxDefaultSize, backend);` and `New( )` returns wxWebView parent. So far I can only invoke functions, which exist in the parent wxWebView class and are overwritten from wxWebViewMiniBlink.

Or have I missed something in that regard?

EDIT:
`((wxWebViewMiniBlink*)m_browser)->SetFocus_browser();`
This is working. Why have I never tried that? Thanks :D

**Comment by imReker** [comment]
XD, I've told you

> wxWebViewMiniBlink inherit from wxWebView, so it's a wxWebView

**Comment by Natulux** [comment]
Yeeees, you did. But in all examples, the engine, that is given to the wxWebView constructor, is referred to as "backend". And therefore I always had the impression that on some background level I change "just" the engine (backend), but still use the wxWebView parent class. I wasn't aware that it worked as if I really had a wxWebViewMiniBlink object... or rather, that the webView can actually be casted to a webViewMiniBlink in that case. Oh well, nevermind. ;-)
