### ISSUE TITLE
No RunScript with two browsers

### ISSUE THREAD

**Issue by Natulux** [imReker/wxWebViewBlink#8]
Hey again
I use miniblink with wxWebViewBlink in a wxFrame as a kind of fancy dialog. I noticed, that when I open a second dialog (two embedded browsers on the screen, but different frame and browser objects), my first browser element is unable to runscript anymore.

In "wxWebViewMiniBlink::RunScriptInternal" I found
`wkeGlobalExec
and
wkeRunJsByFrame`

RunJsByFrame should still be linked to the correct frame, and thats why I get my error message in the correct browser. But could it be, that wkeGlobalExec refers to some sort of global variable? Do you have any experience or ideas with that? Just wild guessing here..

Thanks
Natu

**Comment by imReker** [comment]
I'm afraid I can't help you on this problem. Try ask author of MiniBlink

**Comment by Natulux** [comment]
ok, thanks nonetheless.
