### ISSUE TITLE
wxWebViewBlink performance

### ISSUE THREAD

**Issue by nickware44** [imReker/wxWebViewBlink#9]
wxWebViewBlink works great, but I have some performance issues. CSS animations in wxWebView element with wxWebViewBackendMiniBlink looks slow, with low FPS. How I can fix it? Maybe I need to enable some acceleration?

**Comment by imReker** [comment]
HW acceleration is NOT enabled in the MiniBlink, at least the version used in this project.
Try open an issue in MiniBlink project and see if the latest version supports HW acceleration.

Edit:
Paid version of MiniBlink seems faster than free version.

**Comment by nickware44** [comment]
Ok, thank you.
